CREATE TABLE "authorization"
(
    id                            VARCHAR(255) NOT NULL,
    registered_client_id          VARCHAR(255),
    principal_name                VARCHAR(255),
    authorization_grant_type      VARCHAR(255),
    authorized_scopes             TEXT,
    attributes                    TEXT,
    state                         TEXT,
    authorization_code_value      TEXT,
    authorization_code_issued_at  TIMESTAMP WITHOUT TIME ZONE,
    authorization_code_expires_at TIMESTAMP WITHOUT TIME ZONE,
    authorization_code_metadata   TEXT,
    access_token_value            TEXT,
    access_token_issued_at        TIMESTAMP WITHOUT TIME ZONE,
    access_token_expires_at       TIMESTAMP WITHOUT TIME ZONE,
    access_token_metadata         TEXT,
    access_token_type             VARCHAR(255),
    access_token_scopes           TEXT,
    refresh_token_value           TEXT,
    refresh_token_issued_at       TIMESTAMP WITHOUT TIME ZONE,
    refresh_token_expires_at      TIMESTAMP WITHOUT TIME ZONE,
    refresh_token_metadata        TEXT,
    oidc_id_token_value           TEXT,
    oidc_id_token_issued_at       TIMESTAMP WITHOUT TIME ZONE,
    oidc_id_token_expires_at      TIMESTAMP WITHOUT TIME ZONE,
    oidc_id_token_metadata        TEXT,
    oidc_id_token_claims          TEXT,
    user_code_value               TEXT,
    user_code_issued_at           TIMESTAMP WITHOUT TIME ZONE,
    user_code_expires_at          TIMESTAMP WITHOUT TIME ZONE,
    user_code_metadata            TEXT,
    device_code_value             TEXT,
    device_code_issued_at         TIMESTAMP WITHOUT TIME ZONE,
    device_code_expires_at        TIMESTAMP WITHOUT TIME ZONE,
    device_code_metadata          TEXT,
    CONSTRAINT pk_authorization PRIMARY KEY (id)
);

CREATE TABLE authorization_consent
(
    registered_client_id VARCHAR(255) NOT NULL,
    principal_name       VARCHAR(255) NOT NULL,
    authorities          TEXT,
    CONSTRAINT pk_authorizationconsent PRIMARY KEY (registered_client_id, principal_name)
);

CREATE TABLE client
(
    id                            VARCHAR(255) NOT NULL,
    client_id                     VARCHAR(255),
    client_id_issued_at           TIMESTAMP WITHOUT TIME ZONE,
    client_secret                 VARCHAR(255),
    client_secret_expires_at      TIMESTAMP WITHOUT TIME ZONE,
    client_name                   VARCHAR(255),
    client_authentication_methods TEXT,
    authorization_grant_types     TEXT,
    redirect_uris                 TEXT,
    post_logout_redirect_uris     TEXT,
    scopes                        TEXT,
    client_settings               TEXT,
    token_settings                TEXT,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE session
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token          VARCHAR(255),
    expiring_at    TIMESTAMP WITHOUT TIME ZONE,
    login_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id        BIGINT,
    session_status SMALLINT,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

CREATE TABLE user_table
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);

CREATE TABLE user_table_roles
(
    roles_id      BIGINT NOT NULL,
    user_table_id BIGINT NOT NULL,
    CONSTRAINT pk_user_table_roles PRIMARY KEY (roles_id, user_table_id)
);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE user_table_roles
    ADD CONSTRAINT fk_usetabrol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE user_table_roles
    ADD CONSTRAINT fk_usetabrol_on_user FOREIGN KEY (user_table_id) REFERENCES user_table (id);